# Generated by Django 4.1.7 on 2023-02-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='date',
        ),
        migrations.AddField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
